require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2.1
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
  Exclude:
    - "spec/anki_record/*"

Metrics/BlockLength:
  Exclude:
    - "spec/*"
    - "spec/anki_record/*"
    - "spec/integration/*"

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Metrics/ClassLength:
  Max: 120

Style/HashSyntax:
  EnforcedShorthandSyntax: either

# One expectation per test is a good practice. For this test suite,
# following this rule would have a very high performance cost.
RSpec/MultipleExpectations:
  Enabled: false